// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjlheowuzgvpwdzfudts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqbGhlb3d1emd2cHdkemZ1ZHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzA1NDQsImV4cCI6MjA2MTAwNjU0NH0.ML-HQ5x5hTBajHNCtaiMpVMVg6fG20rDo0Mn1KRkC48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);